#!/bin/bash

APP_PATH=`pwd`
echo " "
echo "|==========================================|"
echo "|                                          |"
echo "| Welcome in the web-framework framework ! |"
echo "|                                          |"
echo "|       web-framework version 0.1a         |"
echo "|                                          |"
echo "|==========================================|"
echo " "

function launch() 
{	
	case $1 in
	 "")
	  APP_PATH=`pwd`
	  ;;
	 ".")
	  APP_PATH=`pwd`
	  ;;
	 *)
	  APP_PATH=$1
	  ;;
	esac	
	echo "the application is located @" $APP_PATH
	
	## Computing of names and classpath with ununderstandable
	
	WAR_NAME=`find $APP_PATH/target -type f -name \*.war`
	WAR_NAME=${WAR_NAME#$APP_PATH/target/} 
	APP_NAME=${WAR_NAME%.war}
	WEBAPP_PATH=$APP_PATH/target/$APP_NAME
	LIBS=$WEBAPP_PATH/WEB-INF/lib	
	LIBS_CLASSPATH=`find $LIBS -type f -name \*.jar` 
	LIBS_CLASSPATH=`echo $LIBS_CLASSPATH | tr ' ' ':'`
	
	## end of computing with ununderstandable bash commands
	
	if (test -e $APP_PATH/target)
	then
		echo " "
		
		## starting the Grizzly server
		
		java -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n \
		-classpath $WEBAPP_PATH/WEB-INF/classes:$WEBAPP_PATH/conf:$LIBS_CLASSPATH \
		cx.ath.mancel01.webframework.grizzly.GrizzlyServerLauncher
		
		## for starting the sun webserver
		
		#cx.ath.mancel01.webframework.sun.WebServerLauncher
		
	else
		echo "target not exists. run 'mvn clean install' to prepare application."
		echo " "
		exit 0
	fi
	return
}

case $1 in
 new)
  echo "not yet implemented"
  ;;
 run)
  launch $2
  ;;
 *)
  echo "display the help :)"
  ;;
esac
