#!/bin/bash

APP_PATH=`pwd`
WEBAPP_PATH=$APP_PATH/target/web-framework
LIBS=$WEBAPP_PATH/WEB-INF/lib

echo "========================================="
echo " "
echo "Welcome in the web-framework framework !"
echo " "
echo "========================================="
echo " "

if (test -e target)
then
	echo "target folder exists, we can start to play :)"
	echo " "
	java -classpath $APP_PATH/target/classes:$WEBAPP_PATH/classes/:$LIBS/activation-1.1.jar:$LIBS/aopalliance-1.0.jar:$LIBS/commons-collections-2.1.jar:$LIBS/commons-logging-1.0.4.jar:$LIBS/dependency-shot-aop-1.0-SNAPSHOT.jar:$LIBS/dependency-shot-api-1.0-SNAPSHOT.jar:$LIBS/dependency-shot-core-1.0-SNAPSHOT.jar:$LIBS/dependency-shot-lifecycle-1.0-SNAPSHOT.jar:$LIBS/dependency-shot-utils-1.0-SNAPSHOT.jar:$LIBS/dom4j-1.6.1.jar:$LIBS/ehcache-1.2.3.jar:$LIBS/groovy-all-1.7.2.jar:$LIBS/gson-1.4.jar:$LIBS/javassist-3.8.0.GA.jar:$LIBS/javax.inject-1.jar:$LIBS/joda-time-1.6.2.jar:$LIBS/jsr311-api-1.1.1.jar:$LIBS/logback-classic-0.9.26.jar:$LIBS/logback-core-0.9.26.jar:$LIBS/mail-1.4.1.jar:$LIBS/slf4j-api-1.6.1.jar:$LIBS/snakeyaml-1.7.jar:$LIBS/xml-apis-1.0.b2.jar cx.ath.mancel01.webframework.sun.WebServerLauncher
else
	echo "target not exists. run 'mvn clean install'"
	echo " "
	exit 0
fi