#!/bin/bash

APP_PATH=`pwd`
echo " "
echo "|==========================================|"
echo "|                                          |"
echo "| Welcome in the web-framework framework ! |"
echo "|                                          |"
echo "|       web-framework version 0.1a         |"
echo "|                                          |"
echo "|==========================================|"
echo " "

function compute_classpath()
{
	## Computing of names and classpath with ununderstandable
	
	#WAR_NAME=`find $APP_PATH/target -type f -name \*.war`
	#WAR_NAME=${WAR_NAME#$APP_PATH/target/} 
	#APP_NAME=${WAR_NAME%.war}
	#WEBAPP_PATH=$APP_PATH/target/$APP_NAME
	#LIBS=$WEBAPP_PATH/WEB-INF/lib
	
	LIBS=$WEBFWK_HOME/lib
	LIBS_CLASSPATH=`find $LIBS -type f -name \*.jar` 
	LIBS_CLASSPATH=`echo $LIBS_CLASSPATH | tr ' ' ':'`
	
	USER_LIBS=$APP_PATH/lib
	USER_LIBS_CLASSPATH=`find $USER_LIBS -type f -name \*.jar` 
	USER_LIBS_CLASSPATH=`echo $USER_LIBS_CLASSPATH | tr ' ' ':'`
	
	SOURCES=$APP_PATH/src/main/java
	RESOURCES=$APP_PATH/src/main/resources
	CONF=$APP_PATH/src/main/webapp/conf
	
	FILES=`find $SOURCES -type f -name \*.java` 
	
	## end of computing with ununderstandable bash commands
	return
}

function launch() 
{	
	case $1 in
	 "")
	  APP_PATH=`pwd`
	  ;;
	 ".")
	  APP_PATH=`pwd`
	  ;;
	 *)
	  APP_PATH=$1
	  ;;
	esac	
	echo "the application is located @" $APP_PATH
	
	if ( ! test -e $APP_PATH/lib)
	then
		mkdir $APP_PATH/lib
	fi
	
	compute_classpath
	
	if ( ! test -e $APP_PATH/target)
	then
		mkdir $APP_PATH/target
	fi
	if ( ! test -e $APP_PATH/target/classes)
	then
		mkdir $APP_PATH/target/classes
		javac -encoding utf-8 -source 1.6 -target 1.6 -d $APP_PATH/target/classes \
		-classpath $RESOURCES:$CONF:$LIBS_CLASSPATH:$USER_LIBS_CLASSPATH $FILES
	fi	
		echo " "
		rm -rf $APP_PATH/target/compclasses
		mkdir $APP_PATH/target/compclasses
		
		## starting the Grizzly server
		
		java -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n \
		-classpath $APP_PATH/target/classes:$APP_PATH/target/compclasses:$RESOURCES:$CONF:$LIBS_CLASSPATH:$USER_LIBS_CLASSPATH \
		cx.ath.mancel01.webframework.integration.grizzly.GrizzlyServerLauncher $APP_PATH
		
		## for starting the sun webserver
		
		#cx.ath.mancel01.webframework.integration.httpserver.WebServerLauncher
		
	return
}

function classpath()
{
	compute_classpath
	echo -classpath $WEBAPP_PATH/WEB-INF/classes:$RESOURCES:$CONF:$LIBS_CLASSPATH
	return
}

function new() 
{	
	case $1 in
	 "")
	  APP_PATH=`pwd`
	  ;;
	 ".")
	  APP_PATH=`pwd`
	  ;;
	 *)
	  if ( ! test -e $1)
	  then
		  mkdir $1
	  fi
	  APP_PATH=$1
	  ;;
	esac	
	echo "the application is created @" $APP_PATH
	cp $WEBFWK_HOME/scripts/pom.xml $APP_PATH
	cp $WEBFWK_HOME/scripts/build.xml $APP_PATH
	cp -r $WEBFWK_HOME/new-project/src $APP_PATH
	return
}

case $1 in
 new)
  new $2
  ;;
 run)
  launch $2
  ;;
 *)
  echo "display the help :)"
  ;;
esac
